services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FLASK_ENV: development
      DATABASE_URL: ${DATABASE_URL}
      TMDB_API_KEY: ${TMDB_API_KEY:-dummy_key_for_development}
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - .:/app

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
